name: Build PJSUA

on:
  push:
    branches: [master]

  pull_request:
    types: [opened, synchronize, reopened]






jobs:
  build-pjsua:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Установка зависимостей (OpenSSL, SWIG и др.)
    - name: Install cirunner
      run: |
        git clone --depth 1 https://github.com/pjsip/cirunner.git
        cirunner/installwindows.ps1
      shell: powershell

    - name: Get OpenSSL
      run: |
        Invoke-WebRequest -Uri "https://github.com/pjsip/third_party_libs/raw/main/openssl-1.1.1s-win.zip" -OutFile openssl.zip
      shell: powershell

    - name: Extract OpenSSL
      run: |
        Expand-Archive openssl.zip -DestinationPath openssl_build
        cd openssl_build
        Add-Content ..\openssl_dir.txt $pwd.Path
      shell: powershell

    # Настройка config_site.h для SSL и других опций
    - name: Configure config_site.h
      run: |
        cd pjlib/include/pj
        cp config_site_test.h config_site.h
        Add-Content config_site.h "#define PJ_HAS_SSL_SOCK 1"
        Add-Content config_site.h "#define PJ_SSL_SOCK_IMP PJ_SSL_SOCK_IMP_SCHANNEL"
      shell: powershell

    # Компиляция проекта с помощью MSBuild
    - name: MSBuild
      run: |
        set /P OPENSSL_DIR=<openssl_dir.txt
@@ -52,12 +51,9 @@ jobs:
        msbuild pjproject-vs14.sln /p:PlatformToolset=v143 /p:Configuration=Release /p:Platform=win32 /p:UseEnv=true
      shell: cmd

    # Сохранение pjsua.exe как артефакта
    - name: Upload pjsua.exe
      uses: actions/upload-artifact@v4
      with:
        name: pjsua-windows
        path: pjsip-apps/bin/pjsua-i386-Win32-vc14-Release.exe
