name: CI Windows

on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CI_WIN_ARGS: -w 3 --shuffle
  CI_MODE: --ci-mode
  CI_RUNNER: python ${{ github.workspace }}/cirunner/cirunner.py -t 3600 -o ${{ github.workspace }}/artifacts --

jobs:
  build-and-upload:
    runs-on: windows-latest
    name: Build and Upload Executables
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install cirunner
      run: |
        git clone --depth 1 https://github.com/pjsip/cirunner.git
        cirunner/installwindows.ps1

    - name: Get OpenSSL
      run: Invoke-WebRequest -Uri "https://github.com/pjsip/third_party_libs/raw/main/openssl-1.1.1s-win.zip" -OutFile ".\openssl.zip"
      shell: powershell

    - name: Expand OpenSSL
      run: |
        Expand-Archive -LiteralPath .\openssl.zip -DestinationPath .
        cd openssl_build
        Add-Content ..\openssl_dir.txt $pwd.Path
      shell: powershell

    - name: Configure Site
      run: |
        cd pjlib/include/pj
        cp config_site_test.h config_site.h
        Add-Content config_site.h "#define PJ_HAS_SSL_SOCK 1"
      shell: powershell

    - name: MSBuild
      run: |
        set /P OPENSSL_DIR=<openssl_dir.txt
        call "%PROGRAMFILES%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
        set INCLUDE=%INCLUDE%;%OPENSSL_DIR%\include
        set LIB=%LIB%;%OPENSSL_DIR%\lib
        msbuild pjproject-vs14.sln /p:PlatformToolset=v143 /p:Configuration=Release /p:Platform=win32 /p:UseEnv=true
      shell: cmd

    - name: Upload Compiled Executables
      uses: actions/upload-artifact@v4
      with:
        name: compiled-exes
        path: |
          pjlib/bin/*.exe
          pjsip/bin/*.exe
          pjmedia/bin/*.exe
          pjnath/bin/*.exe
