name: CI Windows
on: [push, pull_request]

env:
  CI_WIN_ARGS: -w 3 --shuffle
  CI_MODE: --ci-mode
  CI_RUNNER: python ${{ github.workspace }}/cirunner/cirunner.py -t 3600 -o ${{ github.workspace }}/artifacts --

jobs:
  # Основная сборка
  build-pjsua:
    runs-on: windows-latest
    name: Build pjsua
    steps:
    - uses: actions/checkout@v4
    
    - name: Установка зависимостей
      run: |
        git clone --depth 1 https://github.com/pjsip/cirunner.git
        cirunner/installwindows.ps1
        
    - name: Сборка проекта
      shell: cmd
      run: |
        call "%PROGRAMFILES%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
        msbuild pjproject-vs14.sln /p:Configuration=Release /p:Platform=win32
        
    - name: Поиск pjsua.exe
      run: dir /s /b pjsua.exe
        
    - name: Загрузка артефактов
      uses: actions/upload-artifact@v4
      with:
        name: pjsua-binaries
        path: |
          pjsip-apps/bin/*.exe
          pjsip-apps/bin/*.dll
          pjsip/bin/*.exe
